version: '3.8'

services:
  screenshot-server:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "8080:80"
    environment:
      - TARGET_URL=http://192.168.0.1:8080/
      - RESOLUTION=1024x768
      - SCREENSHOT_INTERVAL=60
      - PAGE_LOAD_DELAY=10
      - TZ=America/Toronto
    restart: unless-stopped
    volumes:
      - screenshot-data:/var/www/html

volumes:
  screenshot-data: